*** Settings ***
Documentation     Service Console End-to-End Test Suite
...               Auto-generated by Test Automation Agent on 2026-02-24 06:06:06
...               Operations tested: Health_Check, Upgrade
Resource          common.resource
Suite Setup       Suite Level Setup
Suite Teardown    Suite Level Teardown

*** Keywords ***
Suite Level Setup
    [Documentation]    Setup for the entire test suite
    Verify Service Console Is Installed
    Log    Test suite initialized

Suite Level Teardown
    [Documentation]    Teardown for the entire test suite
    Log    Test suite completed
